name: 'GitHub Action for textlint'
description: 'Display textlint result on GitHub'
author: 'Yutaro Muta'
inputs:
  report-path:
    description: 'The lint report file path.'
    required: false
  textlint-output:
    description: 'The json format output by textlint'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'black'
